#!/bin/sh
# Copyright (c) Yoichi Tagaya
# https://github.com/Swinject/Swinject

files="Sources/Stub/StubProxy/AsyncStubProxy+ArgumentsInitializer Sources/Stub/StubProxy/StubProxy+ArgumentsInitializer"

for file in $files; do
  echo "Generating code to $file.swift"
  erb -v -T 1 $file.erb > $file.swift
done